### ISSUE TITLE
Docs: Clarify which npm script contributors should run when contributing

### ISSUE THREAD

**Issue by cglopez** [smonette/everything-is-okay#19]
First, thanks for having instructions for contributing! Having these instructions helped me get started on contributing to this fun project.

Currently, contributors have two ways to contribute links to happiness (videos/gifs/etc) to this project. Depending on the contributor’s chosen method, that contributor needs to run a specific npm script. Regardless of the chosen method, both npm scripts need to be run in `app/`; otherwise, contributors will get an error stating that npm couldn’t find package.json.

Consider clarifying what steps a contributor should follow when they’ve decided how they’ll contributing their links of happiness. Doing this will ensure that README.md and app/everything-is-okay.json both continue to be updated whenever someone adds a link to happiness.

**Comment by smonette** [comment]
Hey @cglopez! Thank so much for the PRs! 

I did a really haphazard job of plopping the app into a folder to make the root directory more accessible to people who wanted to just causally reference the links or add a few. I genuinely appreciate you getting in there and fixing this!

**Comment by cglopez** [comment]
I'm glad I could help! Thanks for starting this project. So much happiness!
